[Coze]
enable = true

api-key = "pat_IHcP1tCoQAoQumCKoSLEMPjzgsTt9MlWdqTlHYlwx99VUL3ZB5MVIxUpW7ijCCLc" # Cozeçš„API Key
base-url = "https://api.coze.cn/v3/chat" # Coze APIæ¥å£base url
bot_id = "7469333872459726863" #Coze æ¨¡å‹ä½“ID

commands = ["ai", "Coze", "èŠå¤©", "AI","æ‰£å­"]
command-tip = """ -----XYBot-----
ğŸ’¬AIèŠå¤©æŒ‡ä»¤ï¼š
èŠå¤© è¯·æ±‚å†…å®¹"""